const WORD_TYPES = {
    AUX_VERB: 'AUX_VERB',
    CONJUNCTION: 'CONJUNCTION',
    MODIFIER: 'MODIFIER',
    NOUN: 'NOUN',
    NUMERAL: 'NUMERAL',
    PARTICLE: 'PARTICLE',
    PHRASE: 'PHRASE',
    ROOT: 'ROOT',
    VERB: 'VERB'
};

export default WORD_TYPES;
